# Generated by Django 4.0.10 on 2024-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productgallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.PositiveSmallIntegerField()),
                ('horas', models.PositiveSmallIntegerField()),
                ('minutos', models.PositiveSmallIntegerField()),
                ('segundos', models.PositiveSmallIntegerField(default=0)),
                ('imagem', models.ImageField(default='', upload_to='promocao/')),
            ],
        ),
    ]
