# Generated by Django 4.2.11 on 2024-04-01 14:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="logo_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="imagem"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="imagem"
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="imagem"
            ),
        ),
    ]
