# Generated by Django 4.0.10 on 2024-03-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_promocao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocao',
        ),
    ]
