# Generated by Django 4.2.11 on 2024-04-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_logo_image_alter_product_product_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_topSelling",
        ),
        migrations.RemoveField(
            model_name="product",
            name="logo_image",
        ),
        migrations.DeleteModel(
            name="ProductGallery",
        ),
    ]
