# Generated by Django 4.2.11 on 2024-04-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_product_is_topselling_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                max_length=255, upload_to="imagens/", verbose_name="Imagem do Produto"
            ),
        ),
    ]
