# Generated by Django 4.0.10 on 2024-03-23 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='f_name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='l_name',
            field=models.CharField(max_length=50, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tel',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Rio Branco', 'Rio Branco'), ('Maceió', 'Maceió'), ('Macapá', 'Macapá'), ('Manaus', 'Manaus'), ('Salvador', 'Salvador'), ('Fortaleza', 'Fortaleza'), ('Brasília', 'Brasília'), ('Vitória', 'Vitória'), ('Goiânia', 'Goiânia'), ('São Luís', 'São Luís'), ('Cuiabá', 'Cuiabá'), ('Campo Grande', 'Campo Grande'), ('Belo Horizonte', 'Belo Horizonte'), ('Belém', 'Belém'), ('João Pessoa', 'João Pessoa'), ('Curitiba', 'Curitiba'), ('Recife', 'Recife'), ('Teresina', 'Teresina'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Natal', 'Natal'), ('Porto Alegre', 'Porto Alegre'), ('Porto Velho', 'Porto Velho'), ('Boa Vista', 'Boa Vista'), ('Florianópolis', 'Florianópolis'), ('São Paulo', 'São Paulo'), ('Aracaju', 'Aracaju'), ('Palmas', 'Palmas')], max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
