# Generated by Django 4.2.11 on 2024-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_email_alter_account_f_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="tel",
            field=models.CharField(
                blank=True, max_length=11, unique=True, verbose_name="Telefone"
            ),
        ),
    ]
