# Generated by Django 4.0.10 on 2024-03-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_address_remove_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Orçamento', 'Orçamento'), ('Aceito', 'Aceito'), ('Cancelado', 'Cancelado')], default='New', max_length=10),
        ),
    ]
